


server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoban_mvp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456  #${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: xiaoban-test-secret-2026          #${JWT_SECRET:xiaoban-mvp-secret-key-2026}
  expiration: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

ai:
  provider: dashscope
  api-key: sk-ws-H.REXLEYX.tcxY.MEQCIDJb4lUKt1X-TJg_5n4Ne7uU01gqP7A6YPGagzQ411JEAiABwX9mE-OwF11fdksf3mVJQuTONyS6FeWsjM0jtvirxw          #${AI_API_KEY}
  model: qwen-turbo
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  max-tokens: 500
  temperature: 0.7

jpush:
  app-key: 8bc0c3218b934e9a4f38b32a #${JPUSH_APP_KEY}
  master-secret: 5fff0d5fb5f83636beb069ae #${JPUSH_MASTER_SECRET}

weather:
  amap-key: 1cda37a88854dbb8b4ea30ccefdf9476                          #${AMAP_WEATHER_KEY}
  default-city: 440100